import React from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowDown,Code2,Workflow,PenTool,MapPin} from 'lucide-react';
import '../../shared/base.css';
import './style.css';

const discoveryUrl=import.meta.env.VITE_DISCOVERY_URL||'https://adil-khb.github.io/discovery-assistant/';
const projects=window.portfolioProjects||[];
const automation=[
  {n:'01',title:'invoicing, without the busywork.',name:'SAI Vision Services',tools:'Google Apps Script / Google Sheets',problem:'Managing invoices for two brands means keeping records consistent while producing the right document for each business.',solution:'A dual-brand invoicing app built around Google Sheets, with Apps Script connecting the spreadsheet workflow to branded invoice preparation.',outcome:'One shared workflow for two brands.'},
  {n:'02',title:'from project updates to published posts.',name:'Construction & renovation',tools:'Facebook API / workflow automation',problem:'Sharing construction progress competes with the day-to-day work of running projects.',solution:'Facebook API integration to automate posting construction and renovation updates.',outcome:'A repeatable way to share work in progress.'},
  {n:'03',title:'connect the steps. simplify the process.',name:'n8n workflows',tools:'n8n / low-code',problem:'Routine work often involves passing the same information between disconnected tools.',solution:'Automation workflows in n8n that connect triggers, actions, and the tools involved in a process.',outcome:'Less reliance on manual handoffs.'},
  {n:'04',title:'keep the content moving.',name:'Website & content operations',tools:'Website tools / content automation',problem:'Routine website and content updates can turn into a queue of repetitive tasks.',solution:'Automation for recurring content and website update steps, built around the publishing workflow.',outcome:'A more consistent approach to keeping information current.'}
];
function SectionLabel({n,children}){return <div className="section-label"><span className="mono">{n}</span><span className="eyebrow">/ {children}</span></div>;}
function App(){return <div className="site"><a className="skip-link" href="#home">Skip to content</a><header className="site-header"><a href="#home" className="wordmark" aria-label="Adil home">a<span className="teal">/</span></a><nav aria-label="Primary"><a className="text-link" href="#home">-&gt; / home</a><a className="text-link" href="#projects">-&gt; / projects</a><a className="text-link" href="#contact">-&gt; / contact</a></nav><span className="header-location mono">mauritius <span className="teal">↗</span></span></header>
  <main><section id="home" className="hero"><div className="hero-meta"><span className="eyebrow">software engineer & operations professional</span><span className="eyebrow">20°s / 57°e</span></div><h1>adil<br/>khodabacchus<span className="teal">.</span></h1><div className="hero-bottom"><p>hey there! i build clean websites, automation systems, and AI-assisted tools — with a focus on <span>clarity, practicality, and getting real work done.</span></p><a className="explore-link" href="#projects" aria-label="Explore selected work"><ArrowDown size={22}/><span className="mono">explore the work</span></a></div><div className="hero-disciplines mono"><span>01 / software</span><span>02 / systems</span><span>03 / design</span></div></section>
  <section id="projects" className="featured"><SectionLabel n="01">featured project</SectionLabel><div className="feature-heading"><div><span className="eyebrow teal">a better way to begin a project</span><h2>discovery assistant<span className="teal">↗</span></h2></div><span className="project-type mono">hr-tech / interactive tool</span></div><div className="feature-layout"><div className="feature-copy"><h3>good requirements start<br/>with better conversations.</h3><p>An interactive client discovery and requirements-gathering tool, built for HR-tech consulting workflows.</p><p>Consultants gather discovery answers manually and write up requirements documents by hand. This tool turns a structured questionnaire into a live capture flow, then generates a clean requirements document.</p><a className="primary text-link" href={discoveryUrl} target="_blank" rel="noreferrer">-&gt; / try it live <ArrowUpRight size={17}/></a><p className="method-note">Researched and adapted from real consulting methodology. Built to make the process practical.</p><div className="tech-tags mono"><span>react</span><span>local storage</span><span>document generation</span></div></div><a className="feature-visual" href={discoveryUrl} target="_blank" rel="noreferrer" aria-label="Try Discovery Assistant"><div className="visual-top mono"><span><span className="window-dot"/> discovery assistant</span><ArrowUpRight size={15}/></div><img src="./discovery-preview.png" alt="Discovery Assistant showing the Northstar Services sample session, category progress, and captured HR requirements." width="1280" height="720"/><div className="visual-bottom mono"><span>discover → capture → document</span><span>open the workspace ↗</span></div></a></div><div className="feature-foot"><span className="eyebrow">a working prototype, ready to explore</span><p>Try the sample scenario. Edit an answer. Generate a document.</p><span className="mono teal">no sign-up needed</span></div></section>
  <section className="automation"><SectionLabel n="02">automation & low-code</SectionLabel><div className="section-intro"><h2>less repetition.<br/><span className="muted-heading">more useful work.</span></h2><p>Practical systems for the work that happens between the big ideas.</p></div><div className="automation-grid">{automation.map(a=><article key={a.n} className="automation-entry"><div className="entry-meta"><span className="mono teal">{a.n} /</span><span className="eyebrow">{a.name.toLowerCase()}</span><Workflow size={18}/></div><h3>{a.title}</h3><p>{a.problem}</p><p>{a.solution}</p><div className="outcome"><span className="mono">outcome /</span><span>{a.outcome}</span></div><div className="entry-tools mono">{a.tools}</div></article>)}</div></section>
  <section id="about" className="about-section"><SectionLabel n="03">a little about me</SectionLabel><div className="about-layout"><h2>i work where<br/>technology meets<br/><span className="teal">the everyday.</span></h2><div><p>I’m Adil, a software engineer and operations professional based in Mauritius, with a BSc (Hons) in Software Engineering.</p><p>My background spans operations management at SAI Vision Services, entrepreneurship through AKB Contracting, IT, graphic design, and financial auditing. That mix shapes how I build: understand the process, make the information clear, and create something people can actually use.</p><p>I’m interested in the practical side of AI and automation — tools that fit into real workflows and help move work forward.</p><span className="location-line mono"><MapPin size={15}/> based in mauritius · building for everywhere</span></div></div></section>
  <section className="other-projects"><SectionLabel n="04">other projects <span className="project-count">[{projects.length}]</span></SectionLabel><div className="section-intro"><h2>websites. identities.<br/><span className="muted-heading">and everything in between.</span></h2><p>A collection of web and visual design work.</p></div><div className="project-list">{projects.map((p,i)=><details key={p.slug} className="project-entry"><summary><span className="mono project-index">{String(i+1).padStart(2,'0')}</span><span className="project-name">{p.title}</span><span className="project-category mono">{p.externalLabel==='behance'?'visual design':p.externalLabel==='proposal'?'website proposal':'web development'}</span><span className="details-plus" aria-hidden="true">+</span></summary><div className="project-details"><div><h3>{p.subtitle}</h3><p>{p.body}</p><a className="text-link teal" href={p.externalHref} target="_blank" rel="noreferrer">-&gt; / {p.externalLabel} <ArrowUpRight size={14}/></a></div></div></details>)}</div></section>
  <section className="skills"><SectionLabel n="05">the toolkit</SectionLabel><div className="skills-grid"><div><Code2 size={21}/><h3>software development</h3><p>Web development<br/>JavaScript & React<br/>APIs & integrations<br/>Google Apps Script</p></div><div><Workflow size={21}/><h3>operations & process design</h3><p>Workflow mapping<br/>Requirements gathering<br/>Business operations<br/>Financial auditing</p></div><div><span className="ai-icon mono">[ai]</span><h3>Automation &amp; API Tools</h3><p>Low-code automation (Google Apps Script on Google Workspace/Sheets)<br/>API integration (Claude API, Meta Graph API, Google Sheets API, GitHub API)<br/>Prompt design for AI-generated content<br/>Workflow automation (GitHub Actions, scheduled/cron-based pipelines)</p></div><div><PenTool size={21}/><h3>design</h3><p>Visual identity<br/>Graphic & editorial design<br/>Web & interface design<br/>Information hierarchy</p></div></div></section>
  <section id="contact" className="contact"><SectionLabel n="06">get in touch</SectionLabel><div className="contact-layout"><h2>have something<br/>in mind<span className="teal">?</span></h2><div><p>Let’s talk about what you’re working on.</p><a href="mailto:akbcontractingltd@gmail.com" className="contact-link"><span className="mono">-&gt; / email</span><span>akbcontractingltd@gmail.com</span><ArrowUpRight size={20}/></a><a href="https://wa.me/23057086197" target="_blank" rel="noreferrer" className="contact-link"><span className="mono">-&gt; / whatsapp</span><span>+230 57086197</span><ArrowUpRight size={20}/></a></div></div></section></main><footer><span className="mono">© {new Date().getFullYear()} adil khodabacchus</span><span className="mono">built with intention. kept simple.</span><a className="text-link" href="#home">↑ / back to top</a></footer></div>;}
createRoot(document.getElementById('root')).render(<App/>);
